### ISSUE TITLE
The list.txt file cannot be read when executing the py file with an absolute path.

### ISSUE THREAD

**Issue by YTOAA** [Nandaka/PixivUtil2#1091]
If you go to the path where the file is through the cd command and run the PixivUtil2.py file, it reads the list file normally. However, if you run python3/pixiv/PixivUtil2.py like this, the list file cannot be read.
Can you help me out?
The os environment is Linux.

**Comment by PatrickL546** [comment]
You can specify where the list.txt is located in config.ini
`[Settings]`
`downloadListDirectory = .`

**Comment by YTOAA** [comment]
Thank you so much. The problem has been fixed. But I faced a different problem.
python3 /home/naworldw/exthdd/alink/me/TEMPDOWNLOAD/PROGRAM/PYTHON/pixiv/PixivUtil2.py -s 4 0 0 -x
When executing the command, an error occurs because the last -x is recognized strangely.

PixivUtil2.py: error: no such option: -

So if you erase -x, the error appears at the end, but after finishing the desired action, the error is displayed.

Input: Traceback (most recent call last):
  File "/home/naworldw/exthdd/alink/me/TEMPDOWNLOAD/PROGRAM/PYTHON/pixiv/PixivUtil2.py", line 1532, in main
    np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args, options)
  File "/home/naworldw/exthdd/alink/me/TEMPDOWNLOAD/PROGRAM/PYTHON/pixiv/PixivUtil2.py", line 1207, in main_loop
    selection = menu()
  File "/home/naworldw/exthdd/alink/me/TEMPDOWNLOAD/PROGRAM/PYTHON/pixiv/PixivUtil2.py", line 193, in menu
    sel = input('Input: ').rstrip("\r")
EOFError: EOF when reading a line
Unknown Error, please check the log file: (<class 'EOFError'>, EOFError('EOF when reading a line'), <traceback object at 0x7f9ccea240>) 
press enter to exit.Traceback (most recent call last):
  File "/home/naworldw/exthdd/alink/me/TEMPDOWNLOAD/PROGRAM/PYTHON/pixiv/PixivUtil2.py", line 1566, in <module>
    main()
  File "/home/naworldw/exthdd/alink/me/TEMPDOWNLOAD/PROGRAM/PYTHON/pixiv/PixivUtil2.py", line 1553, in main
    input('press enter to exit.').rstrip("\r")
EOFError: EOF when reading a line

**Comment by PatrickL546** [comment]
I think your arguments is wrong. Please read https://github.com/Nandaka/PixivUtil2#command-line-option

**Comment by PatrickL546** [comment]
`-x'` the single quote was a typo. Also removing it didn't fix it. Not familiar with crontab so I don't know else to fix it.

**Comment by YTOAA** [comment]
It's okay because it doesn't work only in the sh file, but it can run with crontab. Thank you for your answer.
