### ISSUE TITLE
ZeroDivisionError on download of bookmarked artists

### ISSUE THREAD

**Issue by nick4949** [Nandaka/PixivUtil2#623]
### Prerequisites

* [X] Did you read FAQ section?
* [X] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description

Proceeding the log-in details..

2020-01-09 10:17:22,134 - PixivUtil20191221 - INFO - Source URL: https://www.pixiv.net/bookmark.php?type=user&p=1
2020-01-09 10:17:23,386 - PixivUtil20191221 - INFO - Using default DB Path: J:\pixivutil20191218\db.sqlite
2020-01-09 10:17:23,389 - PixivUtil20191221 - INFO - Exporting page 1
2020-01-09 10:17:23,389 - PixivUtil20191221 - INFO - Source URL: https://www.pixiv.net/bookmark.php?type=user&p=1&rest=hide
2020-01-09 10:17:24,644 - PixivUtil20191221 - INFO - Using default DB Path: J:\pixivutil20191218\db.sqlite
2020-01-09 10:17:24,646 - PixivUtil20191221 - ERROR - Error at process_bookmark(): (<class 'ZeroDivisionError'>, ZeroDivisionError('float division by zero'), <traceback object at 0x0D5CE0E8>)
2020-01-09 10:17:24,646 - PixivUtil20191221 - ERROR - Traceback (most recent call last):
  File "PixivUtil2.py", line 1216, in process_bookmark
ZeroDivisionError: float division by zero

2020-01-09 10:17:24,648 - PixivUtil20191221 - ERROR - Unknown Error: float division by zero
Traceback (most recent call last):
  File "PixivUtil2.py", line 2382, in main
  File "PixivUtil2.py", line 2104, in main_loop
  File "PixivUtil2.py", line 1703, in menu_download_from_online_user_bookmark
  File "PixivUtil2.py", line 1216, in process_bookmark
ZeroDivisionError: float division by zero
2020-01-09 10:26:32,006 - PixivUtil20191221 - INFO - EXIT: -1
2020-01-09 10:26:32,007 - PixivUtil20191221 - INFO - ###############################################################

### Steps to Reproduce

1. [Successfully Launch PixivUtil2]
2. [Select option 5]
3. [Private: Yes/No both cause same result]
4. [Start: Page 1, End: Page 0 (don't stop)]
5. [Crash occurs]

**Expected behavior:** [Downloads continue as normal]

**Actual behavior:** [Receive Error with only the option to close.]

### Versions

Tested on:
pixivutil20191218
PixivUtil20200103-beta2

**Comment by Akasen** [comment]
I've been getting them as well and it just occurred to me earlier today what the case may be.

I think it may be related to pixiv changing the URL's recently.

So this
https://www.pixiv.net/member.php?id=2179695

is now this
https://www.pixiv.net/en/users/2179695

It's just a hunch here though. Since I know i can do "Download by member id" working, I have a feeling that it's just a matter of the program being unable to parse the new URL's.

**Comment by 811jmk** [comment]
I am getting the same issue.

**Comment by KSuiz** [comment]
A fix has been merged (#624) but all it amounts to is changing `member\.php\?id=` to `en/users/` on line 21 of `PixivBookmark.py`.

**Comment by kantatacanta** [comment]
Having same issue. How can I apply fixed one?

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/PixivUtil2/releases/tag/v20200112

**Comment by 811jmk** [comment]
Unfortunately I'm still getting the same issue. Using the latest version.

**Comment by 811jmk** [comment]
![zerodivisionerror](https://user-images.githubusercontent.com/50151731/72221824-7ceaf080-35a1-11ea-955e-6708a1d76590.png)

**Comment by Nandaka** [comment]
Weird, it does resolve my bookmarks in my pc.
![image](https://user-images.githubusercontent.com/836867/72221963-6e4d0b00-359a-11ea-8d2d-42a89eb23afe.png)

Do you have any bookmarked images in the given url = https://www.pixiv.net/bookmark.php?type=user&p=1&rest=show

**Comment by 811jmk** [comment]
Yes, I do have plenty. The page says I have total 2664 bookmarked artists. :O

**Comment by 811jmk** [comment]
OMG I figured it out.
I changed pixiv language setting to English, and the software looks happy again.
dunno why the language setting affects it though.

**Comment by Nandaka** [comment]
ah, I forgot to pass the locale in this call, that's why it default to English.
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L1224
https://github.com/Nandaka/PixivUtil2/blob/0d09b1748c1f6fd9f8e962e835aa1d2030001882/PixivBookmark.py#L18

**Comment by Nanoka** [comment]
Hello, I'm still getting zero division error from both latest release and source.
pixiv language is japanese

> Error at process_bookmark(): (<class 'ZeroDivisionError'>, ZeroDivisionError('float division by zero'), <traceback object at 0x0D21CEA8>)
> Traceback (most recent call last):
>   File "Y:\PixivUtil2-master\PixivUtil2.py", line 2430, in main
>     np_is_valid, op_is_valid, selection = main_loop(ewd, op_is_valid, selection, np_is_valid, args)
>   File "Y:\PixivUtil2-master\PixivUtil2.py", line 2150, in main_loop
>     menu_download_from_online_user_bookmark(op_is_valid, args)
>   File "Y:\PixivUtil2-master\PixivUtil2.py", line 1745, in menu_download_from_online_user_bookmark
>     process_bookmark(hide, start_page, end_page)
>   File "Y:\PixivUtil2-master\PixivUtil2.py", line 1258, in process_bookmark
>     print("%d/%d\t%f %%" % (i, len(total_list), 100.0 * i / float(len(total_list))))
> ZeroDivisionError: float division by zero

**Comment by Nandaka** [comment]
the beta version should fix the locale issue.

**Comment by Nanoka** [comment]
Unfortunately I still have the problem whenever the site is not set to english, with a fresh v20200120-beta1 directory with only a fresh cookie added to config.ini.
Changing language setting has immediate effect.

I got it working from source while in japanese by changing this in line 34 from PixivBookmark.py:
```python
__re_member = re.compile(locale + r'/users/(\d*)') 
```
To this:
```python
__re_member = re.compile(r'/users/(\d*)')
```

**Comment by Nandaka** [comment]
weird then, what is the resolved in the log file when you starting the script?

**Comment by Nanoka** [comment]
Here is a log: [pixivutil.log](https://github.com/Nandaka/PixivUtil2/files/4101513/pixivutil.log)

**Comment by Nandaka** [comment]
yeah, somehow the return url is to the http://www.pixiv.net, rather than https://www.pixiv.net/en/

![image](https://user-images.githubusercontent.com/836867/72967963-79efcb80-3dfd-11ea-913e-36ad10db15ef.png)

![image](https://user-images.githubusercontent.com/836867/72968100-c0452a80-3dfd-11ea-9f0c-eadb272c7d11.png)
